AppBundle\Entity\Institution:
    type: entity
    table: institutions
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        address:
            type: string
            length: 100
        type:
            type: string
            length: 50
    manyToOne:
        region:
          targetEntity: Region
          joinColumn:
            name: region_id
            referencedColumnName: id

