AppBundle\Entity\InstitutionType:
    type: entity
    table: regions
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        type:
            type: string
            length: 100

