AppBundle\Entity\Role:
    type: entity
    table: roles
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
