AppBundle\Entity\Status:
    type: entity
    table: status
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        status:
            type: string
            length: 100

